### ISSUE TITLE
dotnet restore failed

### ISSUE THREAD

**Issue by TorKlingberg** [AymenDaoudi/NeTraf#1]
I followed the instructions in the readme, but get this error:
```
/tmp/NeTraf-master$ dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
/tmp/NeTraf-master$ ls
~
bin
Helpers
Images
IptrafHelpers
NetstatHelpers
obj
out
Plotter.cs
Program.cs
project.json
project.lock.json
README.md
SettingFiles
ShellCommand.cs
TrafficDataPrinter.cs
```

**Comment by SundeepB** [comment]
I notice the same problem.

Trying `dotnet migrate` produced the following error:

Migration failed.
System.InvalidOperationException: The 'copyToOutput' property cannot be a rooted path.
   at Microsoft.DotNet.Internal.ProjectModel.Files.IncludeContext.CreateCollection(String projectDirectory, String propertyName, IEnumerable`1 patternsStrings, Boolean literalPath)
   at Microsoft.DotNet.Internal.ProjectModel.Files.IncludeContext..ctor(String sourceBasePath, String option, JObject rawObject, String[] defaultBuiltInInclude, String[] defaultBuiltInExclude)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.GetIncludeContext(Project project, JObject rawOptions, String option, String[] defaultBuiltInInclude, String[] defaultBuiltInExclude)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.GetCompilationOptions(JObject rawObject, Project project)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.BuildTargetFrameworksAndConfigurations(Project project, JObject projectJsonObject)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectReader.ReadProject(String projectPath, ProjectReaderSettings settings)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.ComputeMigrationRuleInputs(MigrationSettings migrationSettings)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.MigrateCommand.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommandCompose.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by orwa-te** [comment]
I am having the same issue, did someone find a solution to this problem?
